name: master-build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
  build-linux-dist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set Version Number
        run: |
          export GH_VERSION="v0.2.3"
          export CLEANED_VERSION=$(echo $GH_VERSION | sed "s/v//g")
          sed -i 's/0.0.0/${VERSION}/g' Cargo.toml
      - name: Build x86_64 linux dist
        run: make linux-x86_64-dist
  build-mac-os:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build x86_64 macos Artifact
        run: make mac-x86_64-dist
      - name: Build Arm64 macos artifact
        run: make mac-arm-dist
