name: Publish

on:
  push:
    tags:
      - "*"

jobs:
  build-linux-x86_64:
    name: Publish linux binaries
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Version Number
        run: |
          export GH_VERSION=${{ github.ref_name }}
          export CLEANED_VERSION=$(echo $GH_VERSION | sed "s/v//g")
          echo $CLEANED_VERSION
          sed -i "s/0.0.0/$CLEANED_VERSION/g" Cargo.toml
      - name: Build
        run: make linux-x86_64-dist
      - name: Upload files to a GitHub release
        uses: svenstaro/upload-release-action@2.3.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./dist/linux-x86_64/spake-cli_linux-x86_64.tar.gz
          asset_name: spake-cli_$tag_linux-x86_64.tar.gz
          tag: ${{ github.ref }}
          overwrite: true

  build-macOS-binaries:
    name: Build and publish arm64 and amd64 macos binaries
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Version Number
        run: |
          export GH_VERSION=${{ github.ref_name }}
          export CLEANED_VERSION=$(echo $GH_VERSION | sed "s/v//g")
          echo $CLEANED_VERSION
          sed -i -e "s/0.0.0/$CLEANED_VERSION/g" Cargo.toml
      - name: Build x86_64 artifact
        run: make mac-x86_64-dist
      - name: Upload macOS x86_64 artifacts to release
        uses: svenstaro/upload-release-action@2.3.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./dist/mac-x86_64/spake-cli-mac-x86_64.tar.gz
          asset_name: spake-cli_$tag_macos-x86_64.tar.gz
          tag: ${{ github.ref }}
          overwrite: true
      - name: Build arm64 artifact
        run: make mac-arm-dist
      - name: Upload macOS aarm64 artifacts to release
        uses: svenstaro/upload-release-action@2.3.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./dist/mac-arm/spake-cli-mac-arm64.tar.gz
          asset_name: spake-cli_$tag_macos-arm64.tar.gz
          tag: ${{ github.ref }}
          overwrite: true
      - name: Update Brew Formula repo
        run: |
          export HOMEBREW_GH_TOKEN=${{ secrets.HOMEBREW_GH_TOKEN }}
          python3 scripts/release_homebrew.py ${{ github.ref_name }}
