name: Publish

on:
  push:
    tags:
      - "*"

jobs:
  build-linux-x86_64:
    name: Publish linux binaries
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: make linux-x86_64-dist
      - name: Upload files to a GitHub release
        uses: svenstaro/upload-release-action@2.3.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./dist/linux-x86_64/linux-x86_64.tar.gz
          asset_name: spake-cli_$tag_linux-x86_64.tar.gz
          tag: ${{ github.ref }}
          overwrite: true
