name: Publish

on:
  push:
    tags:
      - "*"

jobs:
  build:
    name: Publish binaries
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Update Build Chain for ARM Macs
        run: rustup target add aarch64-apple-darwin
      - name: Update build chain for x86 Macs
        run: rustup target add x86_64-apple-darwin
      - name: Build
        run: make artifacts
      - name: Upload files to a GitHub release
        uses: svenstaro/upload-release-action@2.3.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/
          asset_name:
          tag: ${{ github.ref }}
          overwrite: true
