name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install dependencies
        run: sudo apt-get install -qq crossbuild-essential-arm64 crossbuild-essential-armhf
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Test compilation of necessary Artifacts
        run: make linux-x86_64-dist
  build-mac-os:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build x86 macos Artifact
        run: make mac-x86-dist
      - name: Build Arm64 macos artifact
        run: make mac-arm-dist
